name: Deploy Batch Lambda to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: Batch-lambda
      run: npm install

    - name: Compile TypeScript
      working-directory: Batch-lambda
      run: npx tsc

    - name: Zip compiled Lambda
      working-directory: Batch-lambda
      run: |
        cd dist
        zip -r ../lambda.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name processCampaignBatch \
          --zip-file fileb://Batch-lambda/lambda.zip
